### ISSUE TITLE
Update SvelteKit version to `1.0.0-next.588` to prep for migration to 1.0

### ISSUE THREAD

**Issue by siudocode** [siuangie91/svelte-pokedex#95]
SvelteKit 1.0 was just released. This app is still on the beta version. 

Before migrating to 1.0, need to update to the last one _before_ 1.0. Probably should do an [`npm install --save-exact`](https://docs.npmjs.com/cli/v8/commands/npm-install#save-exact) for all of these.

## 1. Lock in current version so that `main` uses the exact version.

Update `package.json` so that `npm install` installs the exact version it's on right now, and not `next`.

https://github.com/siuangie91/svelte-pokedex/blob/b719727fd266793fb5343cf59636ba0f5f75f0e1/package.json#L29
https://github.com/siuangie91/svelte-pokedex/blob/b719727fd266793fb5343cf59636ba0f5f75f0e1/package.json#L31

From `package-lock.json`, the exact versions are:

https://github.com/siuangie91/svelte-pokedex/blob/b719727fd266793fb5343cf59636ba0f5f75f0e1/package-lock.json#L2745-L2746
https://github.com/siuangie91/svelte-pokedex/blob/b719727fd266793fb5343cf59636ba0f5f75f0e1/package-lock.json#L2797-L2798

## 2. Upgrade to `1.0.0-next.588`.

1. Upgrade to `@sveltejs/kit@1.0.0-next.405`.
2. Make sure errors are resolved and app works.
3. Repeat with `@sveltejs/kit@1.0.0-next.588`.

Full details in https://github.com/sveltejs/kit/discussions/5774. 

-------------------------

Migration to 1.0 will be done in https://github.com/siuangie91/svelte-pokedex/issues/96

**Comment by siuangie91** [comment]
## Issue after bumping to `1.0.0.next.405`

Running into error where app won't build after running `npx svelte-migrate routes`. No `@migration` errors found. 

Attempted in https://github.com/siuangie91/svelte-pokedex/pull/98.

### 404 happening on all routes

#### `/`
```
Not found: /
Error: Not found: /
    at resolve (svelte-pokedex/.svelte-kit/runtime/server/index.js:3523:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (svelte-pokedex/.svelte-kit/runtime/server/index.js:3402:20)
    at async svelte-pokedex/node_modules/@sveltejs/kit/dist/vite.js:1539:22
```

#### `/pokemon/:name`
```
Not found: /pokemon/leafeon
Error: Not found: /pokemon/leafeon
    at resolve (file://svelte-pokedex/.svelte-kit/runtime/server/index.js:3523:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (svelte-pokedex/.svelte-kit/runtime/server/index.js:3402:20)
    at async svelte-pokedex/node_modules/@sveltejs/kit/dist/vite.js:1539:22
```
